#!/usr/bin/env python
"""publish a draft"""

import os
import sys
import glob
import time


def dst_name(src, dt=time.strftime('%Y-%m-%d')):
    """return the new filename with today's date"""
    today = time.strftime('%Y-%m-%d')
    dst = src.replace('.txt', '.md')
    dst = today + dst[10:]
    return dst


def pubfile(src):
    dst = dst_name(src)
    if os.path.exists(dst):
        print(f'{dst} already exists.')
        sys.exist(0)
    print(f'publishing {src} -> {dst}')
    os.rename(src, dst)


def prompt(zd):
    daft = None
    while not daft:
        for k, v in zd.items():
            print(f'{k}. {v}')
        i = input('Which draft to publish? ')
        i = int(i)
        if i in zd.keys():
            return zd[i]


def main():
    drafts = glob.glob('*.txt')
    if len(drafts) == 0:
        print('No drafts to publish.')

    elif len(drafts) == 1:
        pubfile(drafts[0])
    else:
        zd = zip(range(1, len(drafts) + 1), drafts)
        pubfile(prompt(dict(zd)))


if __name__ == '__main__':
    # print(dst_name(src='2019-01-01-01-hello.txt', dt='2020-04-01'))
    main()
