#!/usr/bin/env python3
"""new draft"""

import time
import subprocess
from pathlib import Path
import sys
import glob

suf = None
if len(sys.argv) > 1:
    suf = sys.argv[1]
today = time.strftime('%Y-%m-%d')
mdl = len(glob.glob('%s*.md' % (today, )))
txtl = len(glob.glob('%s*.txt' % (today, )))
# print(f'{mdl},  {txtl}')
cnt = len(glob.glob('%s*.md' % (today, ))) + len(glob.glob('%s*.txt' % (today, ))) + 1
if suf:
    fname = '%s-%s-%s.txt' % (today, cnt, suf)
else:
    fname = '%s-%s.txt' % (today, cnt)
print(f'New draft file: {fname}')
p = Path(fname)
p.touch()
subprocess.call(['bbedit', fname])
