#!/usr/bin/env python3

import time
import subprocess
from pathlib import Path
import sys
suf = ''
if len(sys.argv) > 1:
    suf = sys.argv[1]
cnt = 1
actsuf = '%s' % (suf, )
while True:
    fname = '%s-%s.md' % (time.strftime('%Y-%m-%d'), actsuf)
    p = Path(fname)
    if p.exists():
        actsuf = '%s%s' % (suf, cnt)
        cnt += 1
    else:
        print(fname)
        p.touch()
        subprocess.call(['open', fname])
        break


